export function normalizeEnergyCostType(value, fallback = 'physical') {
  const candidate = String(value ?? '').trim().toLowerCase();
  if (candidate === 'money') {
    return 'money';
  }
  if (candidate === 'spirit') {
    return 'spirit';
  }
  if (candidate === 'physical') {
    return 'physical';
  }
  if (fallback === 'money') {
    return 'money';
  }
  return fallback === 'spirit' ? 'spirit' : 'physical';
}

export function inferCardEnergyCostType(card = {}) {
  const normalizedType = String(card.type || '').trim().toLowerCase();
  if (normalizedType === 'equipment') {
    return 'money';
  }
  return normalizedType === 'spell' ? 'spirit' : 'physical';
}

export function inferCardCollisionBehavior(card = {}) {
  const normalizedType = String(card.type || '').trim().toLowerCase();
  return normalizedType === 'swarm' ? 'reroute' : 'hold';
}

export function normalizeCollisionBehavior(value, fallback = 'hold') {
  const candidate = String(value ?? '').trim().toLowerCase();
  if (candidate === 'reroute') {
    return 'reroute';
  }
  if (candidate === 'hold') {
    return 'hold';
  }
  return fallback === 'reroute' ? 'reroute' : 'hold';
}

export function normalizeCardDefinition(card = {}) {
  const energyCost = Number(card.energyCost ?? card.elixirCost ?? 0);
  const normalizedType = String(card.type || '').trim().toLowerCase();
  const energyCostType =
    normalizedType === 'equipment'
      ? 'money'
      : normalizeEnergyCostType(
          card.energyCostType,
          inferCardEnergyCostType(card)
        );
  const collisionBehavior = normalizeCollisionBehavior(
    card.collisionBehavior,
    inferCardCollisionBehavior(card)
  );

  return {
    ...card,
    energyCost,
    energyCostType,
    collisionBehavior
  };
}

function baseCard(card) {
  const normalizedCard = normalizeCardDefinition(card);
  const nameZhHant = normalizedCard.nameZhHant ?? normalizedCard.name ?? '';
  const nameEn = normalizedCard.nameEn ?? normalizedCard.name ?? '';
  const nameJa = normalizedCard.nameJa ?? normalizedCard.name ?? '';
  return {
    bodyRadius: 18,
    effectKind: 'none',
    effectValue: 0,
    nameZhHant,
    nameEn,
    nameJa,
    nameI18n: {
      'zh-Hant': nameZhHant,
      en: nameEn,
      ja: nameJa,
    },
    ...normalizedCard
  };
}

export const starterCards = [
  baseCard({
    id: 'swordsman',
    name: '劍士',
    nameZhHant: '劍士',
    nameEn: 'Swordsman',
    nameJa: '剣士',
    energyCost: 3,
    type: 'melee',
    hp: 420,
    damage: 120,
    attackRange: 50,
    bodyRadius: 18,
    moveSpeed: 160,
    attackSpeed: 0.9,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  }),
  baseCard({
    id: 'guardian',
    name: '護衛',
    nameZhHant: '護衛',
    nameEn: 'Guardian',
    nameJa: 'ガーディアン',
    energyCost: 2,
    type: 'melee',
    hp: 320,
    damage: 85,
    attackRange: 50,
    bodyRadius: 18,
    moveSpeed: 180,
    attackSpeed: 0.75,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  }),
  baseCard({
    id: 'knight',
    name: '騎士',
    nameZhHant: '騎士',
    nameEn: 'Knight',
    nameJa: 'ナイト',
    energyCost: 4,
    type: 'tank',
    hp: 980,
    damage: 150,
    attackRange: 70,
    bodyRadius: 24,
    moveSpeed: 140,
    attackSpeed: 1,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  }),
  baseCard({
    id: 'giant',
    name: '巨人',
    nameZhHant: '巨人',
    nameEn: 'Giant',
    nameJa: 'ジャイアント',
    energyCost: 5,
    type: 'tank',
    hp: 1680,
    damage: 190,
    attackRange: 70,
    bodyRadius: 24,
    moveSpeed: 110,
    attackSpeed: 1.2,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'tower'
  }),
  baseCard({
    id: 'archer',
    name: '弓手',
    nameZhHant: '弓手',
    nameEn: 'Archer',
    nameJa: 'アーチャー',
    energyCost: 3,
    type: 'ranged',
    hp: 260,
    damage: 110,
    attackRange: 280,
    bodyRadius: 16,
    moveSpeed: 140,
    attackSpeed: 1,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  }),
  baseCard({
    id: 'musketeer',
    name: '火槍手',
    nameZhHant: '火槍手',
    nameEn: 'Musketeer',
    nameJa: 'マスケット銃士',
    energyCost: 4,
    type: 'ranged',
    hp: 380,
    damage: 180,
    attackRange: 300,
    bodyRadius: 16,
    moveSpeed: 130,
    attackSpeed: 1.1,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  }),
  baseCard({
    id: 'bomber',
    name: '投彈兵',
    nameZhHant: '投彈兵',
    nameEn: 'Bomber',
    nameJa: 'ボマー',
    energyCost: 3,
    type: 'ranged',
    hp: 240,
    damage: 130,
    attackRange: 240,
    bodyRadius: 16,
    moveSpeed: 140,
    attackSpeed: 1,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  }),
  baseCard({
    id: 'wolf_pack',
    name: '狼群',
    nameZhHant: '狼群',
    nameEn: 'Wolf Pack',
    nameJa: 'ウルフパック',
    energyCost: 3,
    type: 'swarm',
    hp: 120,
    damage: 55,
    attackRange: 35,
    bodyRadius: 14,
    moveSpeed: 200,
    attackSpeed: 0.6,
    spawnCount: 3,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  }),
  baseCard({
    id: 'goblin_team',
    name: '哥布林小隊',
    nameZhHant: '哥布林小隊',
    nameEn: 'Goblin Team',
    nameJa: 'ゴブリンチーム',
    energyCost: 2,
    type: 'swarm',
    hp: 95,
    damage: 48,
    attackRange: 35,
    bodyRadius: 14,
    moveSpeed: 220,
    attackSpeed: 0.55,
    spawnCount: 4,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  }),
  baseCard({
    id: 'fireball',
    name: '火球',
    nameZhHant: '火球',
    nameEn: 'Fireball',
    nameJa: 'ファイアボール',
    energyCost: 4,
    type: 'spell',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 130,
    spellDamage: 280,
    targetRule: 'area'
  }),
  baseCard({
    id: 'zap',
    name: '電擊',
    nameZhHant: '電擊',
    nameEn: 'Zap',
    nameJa: 'ザップ',
    energyCost: 2,
    type: 'spell',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 100,
    spellDamage: 140,
    targetRule: 'area'
  }),
  baseCard({
    id: 'healer',
    name: '祭司',
    nameZhHant: '祭司',
    nameEn: 'Healer',
    nameJa: 'ヒーラー',
    energyCost: 3,
    type: 'ranged',
    hp: 300,
    damage: 95,
    attackRange: 220,
    bodyRadius: 16,
    moveSpeed: 120,
    attackSpeed: 1.1,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  }),
  baseCard({
    id: 'asian_parent',
    name: '亞洲家長',
    nameZhHant: '亞洲家長',
    nameEn: 'Asian Parent',
    nameJa: 'アジアの親',
    energyCost: 4,
    type: 'tank',
    hp: 1100,
    damage: 165,
    attackRange: 60,
    bodyRadius: 22,
    moveSpeed: 130,
    attackSpeed: 1.05,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  }),
  {
    id: 'iron_blade',
    name: '鋼刃',
    nameZhHant: '鋼刃',
    nameEn: 'Iron Blade',
    nameJa: '鋼の刃',
    energyCost: 2,
    type: 'equipment',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ally_combo',
    effectKind: 'damage_boost',
    effectValue: 45
  },
  {
    id: 'swift_boots',
    name: '疾行靴',
    nameZhHant: '疾行靴',
    nameEn: 'Swift Boots',
    nameJa: '俊足の靴',
    energyCost: 2,
    type: 'equipment',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ally_combo',
    effectKind: 'speed_boost',
    effectValue: 0.35
  },
  {
    id: 'guardian_armor',
    name: '守衛甲',
    nameZhHant: '守衛甲',
    nameEn: 'Guardian Armor',
    nameJa: '守護の鎧',
    energyCost: 3,
    type: 'equipment',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ally_combo',
    effectKind: 'health_boost',
    effectValue: 180
  },
  baseCard({
    id: 'convenience_shift',
    name: '超商班',
    nameZhHant: '超商班',
    nameEn: 'Convenience Shift',
    nameJa: 'コンビニシフト',
    energyCost: 2,
    type: 'job',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'self',
    effectKind: 'job_part_time',
    effectValue: 10
  }),
  baseCard({
    id: 'delivery_gig',
    name: '外送單',
    nameZhHant: '外送單',
    nameEn: 'Delivery Gig',
    nameJa: '配達ギグ',
    energyCost: 2,
    type: 'job',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'self',
    effectKind: 'job_delivery',
    effectValue: 12
  }),
  baseCard({
    id: 'day_labor',
    name: '粗工現場',
    nameZhHant: '粗工現場',
    nameEn: 'Day Labor',
    nameJa: '日雇い現場',
    energyCost: 3,
    type: 'job',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'self',
    effectKind: 'job_day_labor',
    effectValue: 14
  }),
  {
    id: 'hanger',
    name: '衣架子',
    nameZhHant: '衣架子',
    nameEn: 'Clothes Hanger',
    nameJa: 'ハンガー',
    energyCost: 1,
    type: 'equipment',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ally_combo',
    effectKind: 'hanger_strike',
    effectValue: 5,
    bruiseChance: 0.20,
    mentalChance: 0.01,
    mentalStackRate: 0.01
  },
  {
    id: 'cane',
    name: '藤條',
    nameZhHant: '藤條',
    nameEn: 'Cane',
    nameJa: '藤の棒',
    energyCost: 2,
    type: 'equipment',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ally_combo',
    effectKind: 'cane_strike',
    effectValue: 15,
    bruiseChance: 0.50,
    bleedChance: 0.20,
    mentalChance: 0.05,
    mentalStackRate: 0.015
  },
  {
    id: 'broken_bottle',
    name: '破碎的酒瓶',
    nameZhHant: '破碎的酒瓶',
    nameEn: 'Broken Bottle',
    nameJa: '割れたボトル',
    energyCost: 2,
    type: 'equipment',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ally_combo',
    effectKind: 'bottle_strike',
    effectValue: 20,
    bruiseChance: 0.30,
    bleedChance: 0.40,
    missChance: 0.20
  },
  {
    id: 'western_med',
    name: '神秘的西藥',
    nameZhHant: '神秘的西藥',
    nameEn: 'Mystery Pills',
    nameJa: '謎の西洋薬',
    energyCost: 2,
    type: 'equipment',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ally_combo',
    effectKind: 'western_med',
    effectValue: 0
  },
  {
    id: 'eastern_med',
    name: '神秘的中藥',
    nameZhHant: '神秘的中藥',
    nameEn: 'Mystery Herbs',
    nameJa: '謎の漢方薬',
    energyCost: 1,
    type: 'equipment',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ally_combo',
    effectKind: 'eastern_med',
    effectValue: 0.20
  },
  {
    id: 'electric_swatter',
    name: '電蚊拍',
    nameZhHant: '電蚊拍',
    nameEn: 'Bug Zapper',
    nameJa: '電撃ラケット',
    energyCost: 1,
    type: 'equipment',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ally_combo',
    effectKind: 'electric_shock',
    effectValue: 0.60
  },
  {
    id: 'betel_nut',
    name: '檳榔',
    nameZhHant: '檳榔',
    nameEn: 'Betel Nut',
    nameJa: 'ビンロウ',
    energyCost: 5,
    type: 'equipment',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'hero',
    effectKind: 'betel_nut',
    effectValue: 0.18
  },
  {
    id: 'gua_pi_helmet',
    name: '瓜皮安全帽',
    nameZhHant: '瓜皮安全帽',
    nameEn: 'Half Helmet',
    nameJa: '半キャップヘルメット',
    energyCost: 70,
    type: 'equipment',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'hero',
    effectKind: 'helmet_guard',
    effectValue: 140
  },
  {
    id: 'florida_water',
    name: '明星花露水',
    nameZhHant: '明星花露水',
    nameEn: 'Floral Water',
    nameJa: 'フローラルウォーター',
    energyCost: 12,
    type: 'equipment',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'hero',
    effectKind: 'florida_water',
    effectValue: 24
  },
  baseCard({
    id: 'roadside_elder',
    name: '路邊老人',
    nameZhHant: '路邊老人',
    nameEn: 'Roadside Elder',
    nameJa: '道端の老人',
    energyCost: 3,
    type: 'melee',
    hp: 360,
    damage: 52,
    attackRange: 45,
    bodyRadius: 16,
    moveSpeed: 150,
    attackSpeed: 0.9,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'tower'
  }),
  baseCard({
    id: 'delinquent_89',
    name: '8+9',
    nameZhHant: '8+9',
    nameEn: 'Delinquent',
    nameJa: 'ヤンキー',
    energyCost: 4,
    type: 'swarm',
    hp: 240,
    damage: 80,
    attackRange: 40,
    bodyRadius: 15,
    moveSpeed: 205,
    attackSpeed: 0.62,
    spawnCount: 3,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  }),
  baseCard({
    id: 'mom_gives_money',
    name: '媽媽砸摳',
    nameZhHant: '媽媽砸摳',
    nameEn: 'Mom Gives Cash',
    nameJa: 'ママの小遣い',
    energyCost: 0,
    energyCostType: 'money',
    type: 'event',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'self',
    effectKind: 'event_money',
    effectValue: 10
  }),
  baseCard({
    id: 'pig_brother_alive',
    name: '豬大哥還沒死',
    nameZhHant: '豬大哥還沒死-這是活網仔的勝利',
    nameEn: 'Pig Brother Lives',
    nameJa: 'ピッグ兄貴はまだ生きている',
    energyCost: 0,
    energyCostType: 'spirit',
    type: 'event',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'self',
    effectKind: 'event_swap_card_uses',
    effectValue: 0
  }),
  baseCard({
    id: 'weather_front',
    name: '天氣',
    nameZhHant: '天氣',
    nameEn: 'Weather',
    nameJa: '天気',
    energyCost: 1,
    energyCostType: 'spirit',
    type: 'event',
    hp: 0,
    damage: 0,
    attackRange: 0,
    bodyRadius: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'self',
    effectKind: 'event_weather',
    effectValue: 0
  }),
].map(baseCard);

export const defaultDeckCardIds = [
  'swordsman',
  'iron_blade',
  'knight',
  'archer',
  'musketeer',
  'wolf_pack',
  'fireball',
  'swift_boots'
];
