export const starterCards = [
  {
    id: 'swordsman',
    name: '劍士',
    elixirCost: 3,
    type: 'melee',
    hp: 420,
    damage: 120,
    attackRange: 0.08,
    moveSpeed: 0.16,
    attackSpeed: 0.9,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  },
  {
    id: 'guardian',
    name: '護衛',
    elixirCost: 2,
    type: 'melee',
    hp: 320,
    damage: 85,
    attackRange: 0.08,
    moveSpeed: 0.18,
    attackSpeed: 0.75,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  },
  {
    id: 'knight',
    name: '騎士',
    elixirCost: 4,
    type: 'tank',
    hp: 980,
    damage: 150,
    attackRange: 0.1,
    moveSpeed: 0.14,
    attackSpeed: 1,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  },
  {
    id: 'giant',
    name: '巨人',
    elixirCost: 5,
    type: 'tank',
    hp: 1680,
    damage: 190,
    attackRange: 0.1,
    moveSpeed: 0.11,
    attackSpeed: 1.2,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'tower'
  },
  {
    id: 'archer',
    name: '弓手',
    elixirCost: 3,
    type: 'ranged',
    hp: 260,
    damage: 110,
    attackRange: 0.28,
    moveSpeed: 0.14,
    attackSpeed: 1,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  },
  {
    id: 'musketeer',
    name: '火槍手',
    elixirCost: 4,
    type: 'ranged',
    hp: 380,
    damage: 180,
    attackRange: 0.3,
    moveSpeed: 0.13,
    attackSpeed: 1.1,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  },
  {
    id: 'bomber',
    name: '投彈兵',
    elixirCost: 3,
    type: 'ranged',
    hp: 240,
    damage: 130,
    attackRange: 0.24,
    moveSpeed: 0.14,
    attackSpeed: 1,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  },
  {
    id: 'wolf_pack',
    name: '狼群',
    elixirCost: 3,
    type: 'swarm',
    hp: 120,
    damage: 55,
    attackRange: 0.06,
    moveSpeed: 0.2,
    attackSpeed: 0.6,
    spawnCount: 3,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  },
  {
    id: 'goblin_team',
    name: '哥布林小隊',
    elixirCost: 2,
    type: 'swarm',
    hp: 95,
    damage: 48,
    attackRange: 0.06,
    moveSpeed: 0.22,
    attackSpeed: 0.55,
    spawnCount: 4,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  },
  {
    id: 'fireball',
    name: '火球',
    elixirCost: 4,
    type: 'spell',
    hp: 0,
    damage: 0,
    attackRange: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0.13,
    spellDamage: 280,
    targetRule: 'area'
  },
  {
    id: 'zap',
    name: '電擊',
    elixirCost: 2,
    type: 'spell',
    hp: 0,
    damage: 0,
    attackRange: 0,
    moveSpeed: 0,
    attackSpeed: 0,
    spawnCount: 1,
    spellRadius: 0.1,
    spellDamage: 140,
    targetRule: 'area'
  },
  {
    id: 'healer',
    name: '祭司',
    elixirCost: 3,
    type: 'ranged',
    hp: 300,
    damage: 95,
    attackRange: 0.22,
    moveSpeed: 0.12,
    attackSpeed: 1.1,
    spawnCount: 1,
    spellRadius: 0,
    spellDamage: 0,
    targetRule: 'ground'
  }
];

export const defaultDeckCardIds = [
  'swordsman',
  'guardian',
  'knight',
  'archer',
  'musketeer',
  'wolf_pack',
  'fireball',
  'zap'
];
